// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for VMSpecComputeVcpuThreads.
const (
	N1 VMSpecComputeVcpuThreads = 1
	N2 VMSpecComputeVcpuThreads = 2
)

// Defines values for VMSpecGuestOSArchitecture.
const (
	Aarch64 VMSpecGuestOSArchitecture = "aarch64"
	Amd64   VMSpecGuestOSArchitecture = "amd64"
	Ppc64le VMSpecGuestOSArchitecture = "ppc64le"
	S390x   VMSpecGuestOSArchitecture = "s390x"
	X8664   VMSpecGuestOSArchitecture = "x86_64"
)

// Defines values for VMSpecGuestOSFamily.
const (
	Bsd     VMSpecGuestOSFamily = "bsd"
	Linux   VMSpecGuestOSFamily = "linux"
	Other   VMSpecGuestOSFamily = "other"
	Windows VMSpecGuestOSFamily = "windows"
)

// Defines values for VMSpecGuestOSFirmware.
const (
	Bios           VMSpecGuestOSFirmware = "bios"
	Uefi           VMSpecGuestOSFirmware = "uefi"
	UefiSecureBoot VMSpecGuestOSFirmware = "uefi-secure-boot"
)

// Defines values for VMSpecNetworkInterfacesIpamMode.
const (
	Dhcp   VMSpecNetworkInterfacesIpamMode = "dhcp"
	None   VMSpecNetworkInterfacesIpamMode = "none"
	Static VMSpecNetworkInterfacesIpamMode = "static"
)

// Defines values for VMSpecNetworkInterfacesModel.
const (
	VMSpecNetworkInterfacesModelE1000   VMSpecNetworkInterfacesModel = "e1000"
	VMSpecNetworkInterfacesModelE1000e  VMSpecNetworkInterfacesModel = "e1000e"
	VMSpecNetworkInterfacesModelRtl8139 VMSpecNetworkInterfacesModel = "rtl8139"
	VMSpecNetworkInterfacesModelVirtio  VMSpecNetworkInterfacesModel = "virtio"
	VMSpecNetworkInterfacesModelVmxnet3 VMSpecNetworkInterfacesModel = "vmxnet3"
)

// Defines values for VMSpecStorageDisksBus.
const (
	VMSpecStorageDisksBusIde    VMSpecStorageDisksBus = "ide"
	VMSpecStorageDisksBusNvme   VMSpecStorageDisksBus = "nvme"
	VMSpecStorageDisksBusSata   VMSpecStorageDisksBus = "sata"
	VMSpecStorageDisksBusScsi   VMSpecStorageDisksBus = "scsi"
	VMSpecStorageDisksBusVirtio VMSpecStorageDisksBus = "virtio"
)

// Defines values for VMSpecStorageDisksFormat.
const (
	Thick      VMSpecStorageDisksFormat = "thick"
	ThickEager VMSpecStorageDisksFormat = "thick-eager"
	Thin       VMSpecStorageDisksFormat = "thin"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Error message
	Error string `json:"error"`

	// Type Error type identifier
	Type *string `json:"type,omitempty"`
}

// VM defines model for VM.
type VM struct {
	// Status The status of the created VM
	Status *string `json:"Status,omitempty"`

	// Id ID of the VM
	Id *string `json:"id,omitempty"`

	// Name Name of the VM
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the VM
	Namespace *string `json:"namespace,omitempty"`

	// Path Resource path for this VM
	Path *string `json:"path,omitempty"`
}

// VMInstance VM instance information including status, IP address, and SSH connection details
type VMInstance struct {
	// Ip IP address of the VM instance
	Ip *string `json:"ip,omitempty"`

	// Name Name of the VM instance
	Name *string `json:"name,omitempty"`

	// Namespace Kubernetes namespace where the VM is running
	Namespace *string `json:"namespace,omitempty"`

	// Path Resource path for this VM instance
	Path *string `json:"path,omitempty"`

	// RequestId Request ID (UUID) of the VM instance
	RequestId *openapi_types.UUID `json:"requestId,omitempty"`

	// Ssh SSH access configuration for the VM
	Ssh *struct {
		// ConnectMethods Available methods to connect to the VM via SSH
		ConnectMethods *struct {
			// ClusterSSH SSH command to connect from within the cluster
			ClusterSSH *string `json:"clusterSSH,omitempty"`

			// NodePort NodePort configuration for external SSH access
			NodePort *struct {
				// Node Node IP address or hostname
				Node *string `json:"node,omitempty"`

				// Port NodePort number for SSH access
				Port *int `json:"port,omitempty"`
			} `json:"nodePort,omitempty"`
		} `json:"connectMethods,omitempty"`

		// Enabled Whether SSH access is enabled
		Enabled *bool `json:"enabled,omitempty"`

		// SecretName Name of the Kubernetes secret containing SSH keys
		SecretName *string `json:"secretName,omitempty"`

		// Username SSH username for connecting to the VM
		Username *string `json:"username,omitempty"`
	} `json:"ssh,omitempty"`

	// Status Current status of the VM instance
	Status *string `json:"status,omitempty"`
}

// VMSpec Provider-agnostic virtual machine specification.
//
// This schema is based on industry standards (OVF, CIM) and represents
// compute, memory, storage, and network requirements that can be fulfilled
// by various providers (KubeVirt, VMware vSphere, OpenStack, AWS, Azure,
// Google Cloud, etc.).
//
// Providers translate this abstract specification to their native format.
//
// Note: This schema does not define required fields. Instead, each
// CatalogItem that references this schema can define its own validation
// rules, allowing different catalog items to have different requirements.
type VMSpec struct {
	// Annotations Human-readable annotations (non-functional).
	// Similar to Kubernetes annotations.
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Compute Compute resource requirements.
	// Aligns with OVF VirtualHardwareSection for CPU configuration.
	Compute *struct {
		// Memory Memory configuration (RAM)
		Memory *struct {
			// Limit Maximum memory in GB (optional).
			Limit *int `json:"limit,omitempty"`

			// Reservation Minimum guaranteed memory in GB (optional).
			Reservation *int `json:"reservation,omitempty"`

			// Shares Memory shares for resource scheduling (optional).
			// Higher values = higher priority.
			Shares *int `json:"shares,omitempty"`

			// SizeGB Memory size in gigabytes.
			// Maps to: guest.memory in all providers.
			SizeGB int `json:"sizeGB"`
		} `json:"memory,omitempty"`

		// Vcpu Virtual CPU configuration
		Vcpu *struct {
			// CoresPerSocket Cores per socket (optional).
			// Used for specific CPU topology requirements.
			CoresPerSocket *int `json:"coresPerSocket,omitempty"`

			// Count Number of virtual CPUs.
			// Maps to: vCPU count in all providers.
			Count int `json:"count"`

			// Limit Maximum CPU in MHz (optional).
			// Based on VMware CPU limit.
			Limit *int `json:"limit,omitempty"`

			// Reservation Minimum guaranteed CPU in MHz (optional).
			// Based on VMware CPU reservation.
			Reservation *int `json:"reservation,omitempty"`

			// Shares CPU shares for resource scheduling (optional).
			// Higher values = higher priority.
			// Based on VMware/OpenStack CPU shares concept.
			Shares *int `json:"shares,omitempty"`

			// Sockets Number of CPU sockets (optional).
			// Affects NUMA topology and software licensing.
			// Default: derive from vCPU count.
			Sockets *int `json:"sockets,omitempty"`

			// Threads Threads per core (optional).
			// 1 = hyperthreading disabled, 2 = enabled.
			Threads *VMSpecComputeVcpuThreads `json:"threads,omitempty"`
		} `json:"vcpu,omitempty"`
	} `json:"compute,omitempty"`

	// GuestOS Guest operating system configuration.
	// Based on OVF OperatingSystemSection.
	GuestOS *struct {
		// Architecture CPU architecture
		Architecture *VMSpecGuestOSArchitecture `json:"architecture,omitempty"`

		// Family OS family for provider hints (optional).
		// Helps providers select appropriate defaults.
		Family *VMSpecGuestOSFamily `json:"family,omitempty"`

		// Firmware Firmware type.
		// - bios: Traditional BIOS (broad compatibility)
		// - uefi: UEFI firmware (required for modern OS, Secure Boot)
		Firmware *VMSpecGuestOSFirmware `json:"firmware,omitempty"`

		// Type Operating system identifier (provider-specific).
		//
		// Naming convention: <family>-<version>[-<variant>]
		// Examples:
		// - Linux: rhel-9, ubuntu-22.04, fedora-39, centos-stream-9
		// - Windows: windows-server-2022, windows-11, windows-10
		// - BSD: freebsd-14
		//
		// Providers map this to their image catalog:
		// - KubeVirt: Container image or DataVolume
		// - VMware: VM template or content library item
		// - OpenStack: Glance image
		// - AWS: AMI ID
		// - Azure: Image reference
		Type string `json:"type"`
	} `json:"guestOS,omitempty"`

	// Initialization VM initialization configuration.
	// Uses cloud-init, the industry-standard for VM initialization
	// (supported by all major Linux distros and cloud providers).
	Initialization *struct {
		// CloudInit Cloud-init configuration
		CloudInit *struct {
			// NetworkConfig Cloud-init network configuration (optional).
			// Uses cloud-init network config v2 format.
			NetworkConfig *string `json:"networkConfig,omitempty"`

			// UserData Cloud-init user-data (YAML format).
			// Standard cloud-init configuration for user setup,
			// package installation, and custom scripts.
			UserData *string `json:"userData,omitempty"`
		} `json:"cloudInit,omitempty"`

		// Hostname VM hostname
		Hostname *string `json:"hostname,omitempty"`

		// SshKeys SSH public keys for initial access
		SshKeys *[]string `json:"sshKeys,omitempty"`
	} `json:"initialization,omitempty"`

	// Metadata Custom metadata for extensibility.
	// Allows arbitrary key-value pairs for provider-specific
	// configurations or future extensions without schema changes.
	Metadata *map[string]string `json:"metadata,omitempty"`

	// Network Network configuration.
	// Based on OVF NetworkSection for network interface specifications.
	Network *struct {
		// Interfaces Virtual network interface specifications
		Interfaces *[]struct {
			// Ipam IP address management configuration
			Ipam *struct {
				// Dns DNS servers (for static IP)
				Dns *[]string `json:"dns,omitempty"`

				// Gateway Default gateway (for static IP)
				Gateway *string `json:"gateway,omitempty"`

				// Mode IP address allocation mode
				Mode *VMSpecNetworkInterfacesIpamMode `json:"mode,omitempty"`

				// StaticIPv4 Static IPv4 address (CIDR notation)
				StaticIPv4 *string `json:"staticIPv4,omitempty"`
			} `json:"ipam,omitempty"`

			// Model Network adapter model (optional).
			// Provider selects optimal default if not specified.
			// - virtio: Paravirtualized (best performance)
			// - e1000/e1000e: Intel emulation (broad compatibility)
			// - vmxnet3: VMware paravirtualized
			Model *VMSpecNetworkInterfacesModel `json:"model,omitempty"`

			// Name Interface name/identifier
			Name string `json:"name"`

			// Network Network name/identifier (provider-specific).
			// Examples: "default", "dmz", "internal", "external"
			Network *string `json:"network,omitempty"`
		} `json:"interfaces,omitempty"`
	} `json:"network,omitempty"`

	// Path Resource path for this VM specification
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration hints.
	//
	// Allows providers to optimize resource provisioning while keeping
	// the core schema provider-agnostic. Each provider can define its
	// own hints structure.
	//
	// Common use cases:
	// - VMware: Hardware version, nested virtualization, advanced settings
	// - KubeVirt: Instancetype preferences, dedicated CPU, hugepages
	// - AWS: Instance type hints, EBS optimization, placement groups
	// - Azure: VM size hints, availability zones
	// - OpenStack: Flavor hints, host aggregates
	//
	// Providers ignore hints they don't recognize, ensuring portability.
	ProviderHints *map[string]map[string]interface{} `json:"providerHints,omitempty"`

	// SchemaVersion Schema version identifier for this specification.
	//
	// Format: v<major><stability><minor>
	// - major: Schema major version (e.g., v1, v2)
	// - stability: alpha, beta, or omitted for stable
	// - minor: Minor version number
	//
	// Examples: v1alpha1, v1beta1, v1, v2alpha1
	//
	// This field enables schema evolution while maintaining backward
	// compatibility. Providers can support multiple schema versions
	// simultaneously during transitions.
	SchemaVersion *string `json:"schemaVersion,omitempty"`

	// Storage Storage configuration.
	// Based on OVF DiskSection for virtual disk specifications.
	Storage *struct {
		// Disks Virtual disk specifications.
		// Minimum one disk required (boot disk).
		Disks []struct {
			// BootOrder Boot priority (1 = primary boot device).
			// Only specify for bootable disks.
			BootOrder *int `json:"bootOrder,omitempty"`

			// Bus Disk bus/controller type (optional).
			// Provider selects optimal default if not specified.
			Bus *VMSpecStorageDisksBus `json:"bus,omitempty"`

			// CapacityGB Disk capacity in gigabytes
			CapacityGB int `json:"capacityGB"`

			// Format Disk format (optional, provider-specific).
			// - thin: Dynamically allocated
			// - thick: Pre-allocated (lazy-zeroed)
			// - thick-eager: Pre-allocated (eager-zeroed)
			Format *VMSpecStorageDisksFormat `json:"format,omitempty"`

			// Name Disk identifier (unique within VM).
			// Convention: "boot", "data", "log", etc.
			Name string `json:"name"`

			// StorageProfile Storage profile/class (provider-specific).
			// Examples: "ssd", "nvme", "standard", "premium"
			StorageProfile *string `json:"storageProfile,omitempty"`
		} `json:"disks"`
	} `json:"storage,omitempty"`
}

// VMSpecComputeVcpuThreads Threads per core (optional).
// 1 = hyperthreading disabled, 2 = enabled.
type VMSpecComputeVcpuThreads int

// VMSpecGuestOSArchitecture CPU architecture
type VMSpecGuestOSArchitecture string

// VMSpecGuestOSFamily OS family for provider hints (optional).
// Helps providers select appropriate defaults.
type VMSpecGuestOSFamily string

// VMSpecGuestOSFirmware Firmware type.
// - bios: Traditional BIOS (broad compatibility)
// - uefi: UEFI firmware (required for modern OS, Secure Boot)
type VMSpecGuestOSFirmware string

// VMSpecNetworkInterfacesIpamMode IP address allocation mode
type VMSpecNetworkInterfacesIpamMode string

// VMSpecNetworkInterfacesModel Network adapter model (optional).
// Provider selects optimal default if not specified.
// - virtio: Paravirtualized (best performance)
// - e1000/e1000e: Intel emulation (broad compatibility)
// - vmxnet3: VMware paravirtualized
type VMSpecNetworkInterfacesModel string

// VMSpecStorageDisksBus Disk bus/controller type (optional).
// Provider selects optimal default if not specified.
type VMSpecStorageDisksBus string

// VMSpecStorageDisksFormat Disk format (optional, provider-specific).
// - thin: Dynamically allocated
// - thick: Pre-allocated (lazy-zeroed)
// - thick-eager: Pre-allocated (eager-zeroed)
type VMSpecStorageDisksFormat string

// ListVmsParams defines parameters for ListVms.
type ListVmsParams struct {
	// MaxPageSize Maximum number of results to return per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// RequestId Filter by request ID (UUID)
	RequestId *openapi_types.UUID `form:"request_id,omitempty" json:"request_id,omitempty"`
}

// CreateVmParams defines parameters for CreateVm.
type CreateVmParams struct {
	// Id Optional request ID (UUID). If not provided, one will be generated.
	Id *openapi_types.UUID `form:"id,omitempty" json:"id,omitempty"`
}

// CreateVmJSONRequestBody defines body for CreateVm for application/json ContentType.
type CreateVmJSONRequestBody = VMSpec

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List virtual machine applications
	// (GET /api/v1/vm)
	ListVms(w http.ResponseWriter, r *http.Request, params ListVmsParams)
	// Create a VM
	// (POST /api/v1/vm)
	CreateVm(w http.ResponseWriter, r *http.Request, params CreateVmParams)
	// Health check
	// (GET /api/v1/vm/health)
	ListVmHealth(w http.ResponseWriter, r *http.Request)
	// Delete a virtual machine
	// (DELETE /api/v1/vm/{vmName})
	DeleteVm(w http.ResponseWriter, r *http.Request, vmName string)
	// Get virtual machine applications
	// (GET /api/v1/vm/{vmName})
	GetVm(w http.ResponseWriter, r *http.Request, vmName string)
	// Health check
	// (GET /health)
	ListHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List virtual machine applications
// (GET /api/v1/vm)
func (_ Unimplemented) ListVms(w http.ResponseWriter, r *http.Request, params ListVmsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a VM
// (POST /api/v1/vm)
func (_ Unimplemented) CreateVm(w http.ResponseWriter, r *http.Request, params CreateVmParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /api/v1/vm/health)
func (_ Unimplemented) ListVmHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a virtual machine
// (DELETE /api/v1/vm/{vmName})
func (_ Unimplemented) DeleteVm(w http.ResponseWriter, r *http.Request, vmName string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get virtual machine applications
// (GET /api/v1/vm/{vmName})
func (_ Unimplemented) GetVm(w http.ResponseWriter, r *http.Request, vmName string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) ListHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListVms operation middleware
func (siw *ServerInterfaceWrapper) ListVms(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVmsParams

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "request_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "request_id", r.URL.Query(), &params.RequestId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "request_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateVm operation middleware
func (siw *ServerInterfaceWrapper) CreateVm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateVmParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVm(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListVmHealth operation middleware
func (siw *ServerInterfaceWrapper) ListVmHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVmHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteVm operation middleware
func (siw *ServerInterfaceWrapper) DeleteVm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "vmName" -------------
	var vmName string

	err = runtime.BindStyledParameterWithOptions("simple", "vmName", chi.URLParam(r, "vmName"), &vmName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vmName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVm(w, r, vmName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetVm operation middleware
func (siw *ServerInterfaceWrapper) GetVm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "vmName" -------------
	var vmName string

	err = runtime.BindStyledParameterWithOptions("simple", "vmName", chi.URLParam(r, "vmName"), &vmName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vmName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVm(w, r, vmName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListHealth operation middleware
func (siw *ServerInterfaceWrapper) ListHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/vm", wrapper.ListVms)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/vm", wrapper.CreateVm)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/vm/health", wrapper.ListVmHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/vm/{vmName}", wrapper.DeleteVm)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/vm/{vmName}", wrapper.GetVm)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.ListHealth)
	})

	return r
}

type ListVmsRequestObject struct {
	Params ListVmsParams
}

type ListVmsResponseObject interface {
	VisitListVmsResponse(w http.ResponseWriter) error
}

type ListVms200JSONResponse struct {
	// NextPageToken Token for the next page of results
	NextPageToken *string      `json:"next_page_token,omitempty"`
	Vms           []VMInstance `json:"vms"`
}

func (response ListVms200JSONResponse) VisitListVmsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListVms400JSONResponse Error

func (response ListVms400JSONResponse) VisitListVmsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListVms500JSONResponse Error

func (response ListVms500JSONResponse) VisitListVmsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateVmRequestObject struct {
	Params CreateVmParams
	Body   *CreateVmJSONRequestBody
}

type CreateVmResponseObject interface {
	VisitCreateVmResponse(w http.ResponseWriter) error
}

type CreateVm201JSONResponse VM

func (response CreateVm201JSONResponse) VisitCreateVmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateVm400JSONResponse Error

func (response CreateVm400JSONResponse) VisitCreateVmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateVm500JSONResponse Error

func (response CreateVm500JSONResponse) VisitCreateVmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListVmHealthRequestObject struct {
}

type ListVmHealthResponseObject interface {
	VisitListVmHealthResponse(w http.ResponseWriter) error
}

type ListVmHealth200TextResponse string

func (response ListVmHealth200TextResponse) VisitListVmHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type DeleteVmRequestObject struct {
	VmName string `json:"vmName"`
}

type DeleteVmResponseObject interface {
	VisitDeleteVmResponse(w http.ResponseWriter) error
}

type DeleteVm204Response struct {
}

func (response DeleteVm204Response) VisitDeleteVmResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVm400JSONResponse Error

func (response DeleteVm400JSONResponse) VisitDeleteVmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVm500JSONResponse Error

func (response DeleteVm500JSONResponse) VisitDeleteVmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetVmRequestObject struct {
	VmName string `json:"vmName"`
}

type GetVmResponseObject interface {
	VisitGetVmResponse(w http.ResponseWriter) error
}

type GetVm200JSONResponse VMInstance

func (response GetVm200JSONResponse) VisitGetVmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVm400JSONResponse Error

func (response GetVm400JSONResponse) VisitGetVmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetVm500JSONResponse Error

func (response GetVm500JSONResponse) VisitGetVmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListHealthRequestObject struct {
}

type ListHealthResponseObject interface {
	VisitListHealthResponse(w http.ResponseWriter) error
}

type ListHealth200TextResponse string

func (response ListHealth200TextResponse) VisitListHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List virtual machine applications
	// (GET /api/v1/vm)
	ListVms(ctx context.Context, request ListVmsRequestObject) (ListVmsResponseObject, error)
	// Create a VM
	// (POST /api/v1/vm)
	CreateVm(ctx context.Context, request CreateVmRequestObject) (CreateVmResponseObject, error)
	// Health check
	// (GET /api/v1/vm/health)
	ListVmHealth(ctx context.Context, request ListVmHealthRequestObject) (ListVmHealthResponseObject, error)
	// Delete a virtual machine
	// (DELETE /api/v1/vm/{vmName})
	DeleteVm(ctx context.Context, request DeleteVmRequestObject) (DeleteVmResponseObject, error)
	// Get virtual machine applications
	// (GET /api/v1/vm/{vmName})
	GetVm(ctx context.Context, request GetVmRequestObject) (GetVmResponseObject, error)
	// Health check
	// (GET /health)
	ListHealth(ctx context.Context, request ListHealthRequestObject) (ListHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListVms operation middleware
func (sh *strictHandler) ListVms(w http.ResponseWriter, r *http.Request, params ListVmsParams) {
	var request ListVmsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVms(ctx, request.(ListVmsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVms")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVmsResponseObject); ok {
		if err := validResponse.VisitListVmsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVm operation middleware
func (sh *strictHandler) CreateVm(w http.ResponseWriter, r *http.Request, params CreateVmParams) {
	var request CreateVmRequestObject

	request.Params = params

	var body CreateVmJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVm(ctx, request.(CreateVmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVmResponseObject); ok {
		if err := validResponse.VisitCreateVmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVmHealth operation middleware
func (sh *strictHandler) ListVmHealth(w http.ResponseWriter, r *http.Request) {
	var request ListVmHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVmHealth(ctx, request.(ListVmHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVmHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVmHealthResponseObject); ok {
		if err := validResponse.VisitListVmHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVm operation middleware
func (sh *strictHandler) DeleteVm(w http.ResponseWriter, r *http.Request, vmName string) {
	var request DeleteVmRequestObject

	request.VmName = vmName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVm(ctx, request.(DeleteVmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVmResponseObject); ok {
		if err := validResponse.VisitDeleteVmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVm operation middleware
func (sh *strictHandler) GetVm(w http.ResponseWriter, r *http.Request, vmName string) {
	var request GetVmRequestObject

	request.VmName = vmName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVm(ctx, request.(GetVmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVmResponseObject); ok {
		if err := validResponse.VisitGetVmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListHealth operation middleware
func (sh *strictHandler) ListHealth(w http.ResponseWriter, r *http.Request) {
	var request ListHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHealth(ctx, request.(ListHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHealthResponseObject); ok {
		if err := validResponse.VisitListHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
