// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWwW7bOBD9FYK7R9myHSfd1S1xg6zROg2SjS9FD2NpbLGlRGZIOTUC/fuClOzEktxt",
	"F+miQHKjxeG84XuPM37gscq0yjG3hkcP3MQpZuCXE1kYi3SNRhUUo/ukSWkkK9AHwBqEhIXEiS7c7wRN",
	"TEJboXIe8b+VBclAShWDdVEsrhKyydUtDzh+hUxL5BHnAbcb7VbGkshXvAwec88wU7T5kfRZdeK7EW6s",
	"Iljhj0CY+si3McrdF7X4jLHlAf/aA9Q92lFqqcAy4OdEitoExyrpKMsHM7/3BH88GOzgRG5xheRuidvM",
	"XTkyNKa6RrtywrtCECY8+lgn+dS8Thnw+axdtUjaeNO3TC2ZTZHNZ3usDUdHOD4+edPDP/5c9Iaj5KgH",
	"4+OT3nh0cjIcD9+MB4NBl3o5ZB3UXEKGB4DucWGQ1kiHshkN8YGUfmsv739Wej67xrsCje1Qu+sVTa5u",
	"2VJRx42GXXK/QO4Drsw063zAZ2CQCbe3TfDhZq+wuwI2faHCWOUWRI6UCPPFhEtMFEEkwTqhOhAJsjba",
	"NWQ7qRotrkOr77WMCxT5UlX9ILcQO+uUQQP8XbHAuSDLrkitRYLETq+mPOBSxJgbz00lGz/VEKfIRn2n",
	"bUGSRzy1VpsoDO/v7/vgt/uKVmF91oTvp5Pzy5vz3qg/6Kc2k44CK6yn8BDwGslUpa2HIHUKQy+Vxhy0",
	"4BE/6g98BRps6u0fpgjSpm65Qtum9y+/zeIU4y+e5x3yDdJaxNiswL0tcIenCY/4e2FslYK75ma0cldz",
	"MKPBoI324Z2XyBRZBm787MH7rXA9DOt5cLDmC7TMiUeZL4TBQhV2N0W2SptWsRdoG9PXHKjaWQJzDw1a",
	"SxH7JOFn4/C349ytfidc8oj/Fj7O+7Ae9mFz0nvTtfkI+PEzglYzrwNqmlukHCSregbDOvCpGo7YJo1P",
	"md4ptK4fqkTb0SDe+u8MHr305D4tVapo34OoauJnKtk8GyGPo6HcH8D16GjIP35G4C4ZLhWb1NnLgI//",
	"D+XPIGG05eAXctvWJvmePcrg8KMHNp9900sXaGsj/aQ33S1q9YxftJiVPGtBtgDJMohTkWNTWK1Mh7IT",
	"Qmj7oCltFfWrtInhq6N+tqO2tnB/T513ig7r3OoE9ifNvzSIU63l5qWYqGIneR04taO2bmkMHB/kTxke",
	"fXyo/72HvPxU/hMAAP//CgkcvcgRAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
