// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa63PbNhL/V3Z4nWlyJfWyk9T6cuNHmqgJnVxsK9NWPg9EriTEIMACoB5x/b/fACAp",
	"UaQt+9qk+XDfJDwXi93f/nbBGy8SSSo4cq28/o2nohkmxP48jCJU9heJY6qp4IS9lyJFqSkqr69lhr4X",
	"o4okTU231/eGIRA7DSLBJ3SaSWJ7fC/dmHnjKTW7SrMxo9HVNa5MS3Wds7PX4PrhGlcwERLKpVsjPuCf",
	"MNIYw5wSiJjI4oByqtv255gotH9hvIJUijmNUZpZI/4+/wcJSVPKp/0RD+BNNsYhlbq/sRJkCuUJ0cQM",
	"OPx41rdipIRK2/A5k9iHqpCm49Xx+z5QrjThEUKCmsT5GsNwQcycaYZKQ5QpLRL62SpnZNSDS5KkDL2+",
	"UU2Ace/Zs+4BHB4eHh7vnX4mx13268mge3r+8plpG7x0w1utlud7epXaiVpSPvVub8sWMTZq8m5971gk",
	"ieA/UWSxqmvb9cLEdgPlEctijIFyIIyBQjmnEYJZFFSKEZ3QyEpulHo+Q4WFmmGOUlHBKZ/6gEuNXNEx",
	"ZVSvfCA8Lm8jKJapmklrVLeUQonm93cSJ17f+0d7bbPt3GDbZ07KsBh+axeyu13NaG7d9y1Q2MZrO/jW",
	"9/JzXzllPmj3czPUXIDE3zMqMfb6v1XX8dcHumy4pxOqrh/pcVTqjDCIqbqu3k5NlRFJSUR1g7uZbaHo",
	"hgXVM8iMF6hsMqFLeBIe+fDqyIfzo6cVW+12Oq+OzD5Ea5Rmpf/81gkOLn94Eh798eroj/Ojp9/VDdT3",
	"OEnwDilojFzTCUUJTzJOf8/QykM5DMOnzt5ACqFhLliWICSZ0jBGMEvGMPLGQuiR1xrxw1KFVjcKIsKN",
	"W9uRChi9Rhh51j89H0YeE1PzA3XU2vJIs+TWIUnw2ZzzSf4juPxn0fT0X981uuSmRdjj++v7aLKEl1IK",
	"WdfRh5+O4cWPnRdgjJBRwjWgGQkSVSq4wtqtx6gJZfWVXmcJ4YFEEpMxQ8Blygi3hlOaEWgBekYViCjK",
	"pEQeYUUx5i6+N4f53mEHUAXFOWGcaVgQBVzowu/jJlso4LIu4cWHAUicoN3YxgArTCmdO/gdsrVtr2p3",
	"e3u4/+z5iwB/PBgH3V68F5D9Z8+D/d7z59397ov9Tqfj+d5EyIRor+9lkgblpk3yKk101gCir8/P34Pr",
	"hEjEFWn2O51yJco1TlGapTTVrOHcZzMhNcyq96OyJCFyBWICemYBd8wwqRx5wOeE0RgGPM10k+gFkt2n",
	"5tz/VpRP7UZOyTl2rfeaaZ2qfrsdR0krb21FIim0Tp0oAc1Feah6txwl39bpqclLXplw+u7scZBpJ4EZ",
	"Q7Q5plopjUktFBUBQRm2YHXx7swFQesWSCXQhEwRIqIJE9Om6NWs8XfbW69Bz9KUU5KYzkjwuWkXvA+j",
	"rNPZi2KqtBT2NwauKY+4rm3Ec2KgLLN5S3m27IOcIQsOfMjGGddZ0Ou1Ovs+TDAWkgR7Bz5EyLVQgdIS",
	"SRIcmKkfKY/FQvVh4X4EJoqhDHqdXs8vG7vdTVZVKIqqOzS0RbeOBdeEcixGCQmGcg0tsG+SpmEIGpOU",
	"EW0HRYJr5BoYHUvjElRjUvK0w3AAg5MNljawa5c2t4XtTjcPM8QmA3yNhOlZAxrY9gIPFOVThlpwA9Mi",
	"k1EdplPStMwx4YLTiDAw/YXzbyyyPom49ozMJH7H2aow/Iej16a89XV3UUzfWwYE06CUzJ3IxEtl9Ddz",
	"arr0vZRlkjCDILbJ7FVqp5DaNGSMyHLUhgSOTBXUrmXwh4p2PswIFmIi5OpxiODmVBEAnnw4DJ/WMxf6",
	"ucGj8wVM5/30qTXiIUmtg7hUIHEzc669ma5Umdbz/4FobRNRI3qTEVep752au1+jtVW3MS8nY7tzgBE/",
	"ZEwsFBiPN5FjPVShNriprJJFpmEskVwbsEyF1MTlGhXsNozP8n/jOSuQGIkpN9dk8hE65UIiZPyaiwV3",
	"46wAb3ClgMgysZEbEK3gCbamLR+uszHOqdQ+zBMDVD6QhTI3PCQsw+r8O04LTl3b133jkYVVeEGOzp1y",
	"9V5ryYicotFvsX3DuKzbKoc52cygebIcumhhDOpFc6a4nUfVGWju4mV6a5lZoR6XeljlTsUcJTdStUb8",
	"QhlKuHpAQlnzOEbGyO41yxrKVSV+g6tgbq7EJvDKMUkynRqzMYJOKNNoprZG/Ejomcnmle2Zu4sscgy3",
	"Qf2ykM+pFDxBbihOKkWcRXkGJhYcDY6VpqyRJF6T4ptzolLbprvKE8JcqmqWZOKDzXBSYhVfQZFkFcQ4",
	"D+aGNyZk+Rb51ESd53u+l1Be/O3ekesE+a/H5zqXdxvaeSNDOts0keqpyTUqR4HJigkSg0I2Cdz0cXGl",
	"yA1pViBFZvCibdnoRo0BeZYY6awmooKHeL7NB8fEplERy5S2jXomEa80RXlF0vQqxkSYI631apepWeGZ",
	"FpJM8XGhKJ+0o35mM9q62u4uBjhY++AuxhiqY4jWhvLzA9HAkBhqzNEtUU2q8xSskn+bRU6KoWtPqdvk",
	"MLTMVmjsg8kbzZJuE7kWyiSQyCdCRhgbcUiasgJSGM6RudszhG9nPceWUm6tYQ/c+G55R0RKsqqZqlNq",
	"k60OQ3uJjL2beP3f7t93GJ6lGHm3/s2DGF7p4JbgrU3dq9rXgxPZHQywjjyXd1WUQhLNKM/5jBXe/0ZP",
	"dD/3NFvdzJMrGt9WCOg8KchnzjUrXtzMM+eJ3XAYvqVK14/+nkwpJxpjYNT40QSGoaqpjeNSX6Vkilda",
	"XCOvL3Numq23SdSS4rxIxs1MSG2uNDFZQMZ0lazj6uf01+PB88Gnl6uwd9E5Pf9l7+3Hi/13Hwc6PP/5",
	"Olx1Z6cnF7235/9enX76ZXl68nLv9ORwER7/fNAEYXPnZw9yuGG4EdfWHtbgTNZBHuxQldq1cav7wLSq",
	"aVI+Ydy3Qf7Qcet7lpJfiZ0zirKDgZcy3bhvQp6U2ASsDAr3FpTzYeYOojTbqXszZhvP7MRSwvXWG+e8",
	"3A0HBZUOyJQLpWkE8xwgkhwgKoHGxpmBe0JQEFVeFp5slsL9kkD6UK3UPx3xlGUKhuGaNecrTGz6n6SZ",
	"Rh/y87inhe1yTqtamdCScGULCLY+QcZKSxLpquzrsgUnms5tzTEh2gWduh3n9/L4Wv3x+4sd8T0SGW/A",
	"l9MsGaM0zj9fL6U2csq5WzozofT+jHLfRkaaGB7UrRcnt0zJyVO3lltbwJ0IJzPXJDJS1xl4XvOBgteV",
	"D3GH7wee7zEaIVfWKRwN9g5TEs0Qei0TATLJNkqOi8WiRWx3S8hpO5+r2m8Hxy9Pz14GvVanNdMJ26iw",
	"7hRgXuZF8y5h6Yx0zWyRIicp9freXqvT2nf598xeUFFx6N94U9R31lOiGUbX1mp3SZDbr+CD2Ot7r1C/",
	"LiofRWXf7tvrdApdo7OQDY7U/qQEX7/i7gKN10XRpJ6sv7EWkNect45jfIFMK2UdM7idx4pGdXxAnUmu",
	"gJSBcQtEVE0FJsLm0ZNIkqBGqWys2Kq8kKUxYuCla+RxEVKUNlYawmhG/p6hhcHcwhKydEHYlkX8DZ3F",
	"OCEZ016/2+nYPCn3EvvvXp+5O5Cnjhk4X28SZ4MPbMqyTXYuv6A95KymwR7OMhsiJxmD8pKMg+zfu3v+",
	"RvHD46RwD18NQhyR2OYKqPLyUn5LX2v/C47L1H12gPmYTRcxurOI64y2cJF54l3e+l4qmvjisUQTkghw",
	"XGx7RP7WOQxhQRkzSZWFcgNTGINwWVWJKnmy6kC+6khuk2G4y5PKCt0whMFJUdVJUmGL7ZFZ5W7zpXHF",
	"bNfvPRltePVzZmyv8kjEq7/Qgt3FrUOXCcO3NZ/p/uU71j6DsfrCGFTpOmz11V2meBF0z3B294Ovt/ux",
	"4BNGIw2Bs2I9c+TLlrIIM3ndCnBJlfveYr/X+3qyDcuCEOAywrRAtG8NVUqEsP5bAZU85prcdhDfOnBh",
	"qJs+rLDtQGrMfSJFYnFkXeuqYoebuRs7Lly9Z+PjjfypahgaWpoLlkNHXkvIkcNI72277KOxpOLe+w2V",
	"sTAX4hvxyMEJqMxsg7GTYf8r2n5oP8qYiIzH36LNl+Zat3m/mV6+Qt1g3eMVUK2KWuTgpIll/ynT/moG",
	"3fnC8eqb4Hf/d43druEMvckvTICvf9qTxjZ6cBdmKZ/ewTKNzUJeqbdlW1vIT4iOZpXZw7CJYR6mKVv9",
	"6SCRWWG/pE/9fYSz8+UJp1Pft0c4/0bv/bvYboXgUvfV6XgFhAs9QwmuUP6tQUuBFU1MM/8aunBrV49r",
	"k5S21+Wyy3LSzY4HJVl+QUA4mdqHv01P9+p1lEo1rcQetZ5VfP9zefvfAAAA//+3vUJM0TAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
