// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbXPbOJL+K124qdrklpQl2Uk2+nLll2yiSeT4YltTuyOfCyJbEsYgwAFAvcSr/34F",
	"gKREibbinViTD/spMgmgm/3y9IMGck8imaRSoDCadO6JjiaYUPfznVJS2R8x6kix1DApSId8+fspvPlb",
	"8w3YiZxRYQDtSFCoUyk0koCkSqaoDEPt5xvK+PZKH7KEilAhjemQI+A85VRQ+xJ0ihEbsQiMBDNhGmQU",
	"ZUqhiOzyOKdJypF0yNUE4S+CJvgXGDHkMTANCn/PmMIYhpmBGdUgpIFUySmLMSYBMYvUTtVGMTEmy4Aw",
	"oQ21K29peP2lCwpH6ATDSCqvTKmd//AHdDtwb/VBq32IR69evwnxb2+HYasdH4b06NXr8Kj9+nXrqPXm",
	"qNlskoCMpEqoIR2SKRaWQuv01YaaTNfY8+rqAvxLiGRc0eao2SxXYsLgGJVdyjDDa777ciKVgUnVPzpL",
	"EqoWIEdgJmgtOuSYVD65K6aUsxi6Is1Mner+weNmZjEKw0YLJsZOkDeym7kua2JMqjsHB3GUNPKnjUgm",
	"hdWZVyVkuSrfat5lQIoAIp1fSS7W2+mmHC2Hv2Fk7Bd9QMrNpMYZ7nnhDs3EmKORwmaJzFS0nSUprVvm",
	"lAopWEQ52PeF7dcWWRlE3hGrO40/C74gHaMyfErwrOu7ve62laqWCMg8pJiGpWb+iwwqoa0dJ95MNwFJ",
	"eaYotw50j6ys0jqF1vZBxqkqR61pgGrKIszzWTWs+5k8yIdZxfo9K5xy/nlEOr/ek58UjkiH/NfBCukO",
	"cpizwROmStpPuI2ooVyOw4QKOkZ1q3CkbydIY32bUCZuacpupy3K0wlt3eZqWKX07TS5tZBw2+9dphiR",
	"5U2wYdw+UyajHHo0mjCBEOOICYtQC8ilQi4V8jW+LTq+5Nb2wZEnDkNV8d80+WYM2hE9y11etqLup8kt",
	"i5cVV0+Tws25V6fJTo9Ok9ybn5g2259+QcdMUIMxcKaNTYx+T2+ZTeDc3KZ0jLdG3qHYXubKPnbIrtAo",
	"htMCdexMsDPt0gp1xk01LXDxc/rP0+7r7m/vFr32dfP86h+Hn365Pvr8S9f0rn6+6y1ak/Oz6/anq/9d",
	"nP/2j/n52bvD87PjWe/057d10Ght1LknzKD/8VjY9nsrMCVUKbqoScllQL5PeEcySaS4PXX//N2W2Rr8",
	"8G99FdbARMSzGGNgAijnkK/nULwsn67U68ZAXE1QY1GiYYpKMymYGAeAc4NCsyHjzCwCoCIuhqmwrMKR",
	"FCM2zpRbrzEQW1GQoKExNXSXWb+ruS79s14he+m0cqp/YDnb2psyFxXJtgz4QVd5Pd63VZzczVq7rlOw",
	"ctrNcwf2xaZbaBwzG0uUX1TiqP55BSrXVKykx+fUT/yG8B2IY87lTEPKqbG0ZTVUozFMjDXMmJnIzMBQ",
	"Ib2zkJVKZahPk8ZAFF+kIdMIE/tdFtQWoDCSY8G+okslNhZSIWTiTsiZ8OOcAh9xoYGqMifVWm3R8AIb",
	"40YAd9kQp0yZAKbJjCoMgM70y8ZA9CnPsDr/ga8Fby7tk7bE1ntCZx4Mc2buw5SYw8acUzVGa99CfM24",
	"rNUoh3nd7KBpMu97aCEd0nqzB8TchICH63cR7K4SFbb2AOk8NZZTVMJ+YmMgrrWnDruBdQsJOR0ifzTG",
	"t+pSVeOPuAin1r+QUqa03xPR8djGoFV0xLhBO7UxECfSTODOhZKIYeqjIsm0gSGCF7DteRRTpqRIUFiy",
	"nioZZ5GTHRA5E2jJQ5kXBmlC6rxod4SPWNu+XovoxkD0cq0ywX7P0KUXE54H0AR1Sp3hK/U/WYQxTkPH",
	"ZBI6/4RibCna68OAJEwUf7aCgiCRDvm/X2n4tRm+vXnxa5j/+u/i0cv/+WnnZsR91s2eovaqdqt2uR5v",
	"VRPSO9R+Z0gXXNIYNPJR6KcPi/hAYfeSGpTMLJIduE3aWuFGkSWeSZKARFIYyoTjszY7htR1FyKeaYPK",
	"WmKd5daRqu/L74+jCPXOSrBB/XtA3bQq8m1lptaTi2zIWfQRFzVmv/wAqXttE8plXblwYyC6wn4hxjBl",
	"FCIuM7vvZebA/bRWc39azCgA2eN8UScgoWnKxLgzECF8zIZoNyydtZVsHVFn1FA74PiXy45Tw0KAe/A1",
	"U9iBqpL2xfvTiw4U4FyCnH3T71lY7sA4Q20gyrSRCfvqTLORZ1pPQozbr1613sLx8fHx6eH5V3ra4v88",
	"67bOr969ss+67/IGQKPxDXvV7x4XZ0zfPTEq8g1hzPRdFba3AiOiKY2YqQkKKxaK1w6zLH4Z0NloxObw",
	"oncSwPuTAK5OXlYs2mo235+QKjBZCPrri97Jv96f/Ovq5OVPdclUj6pOixUSwIsqhvZ7Lz3DByWlgank",
	"WYJlFbBLxjAgQynNgDQG4rg0obONhogKR2IcDgNndwgDBwYDEsCAcDm2P9BEm/hslyQPoK//Ef4b6Bus",
	"/HHz7HH13ibH58unhZabBHYMtQgLeqENJlssc0URE5o62P586VHdtVyRKWCJ3f7mn1HHJuq7eZ83RVfK",
	"xECc08S+jKSY2udSdGCQNZuHUcy0UdL9xtA/yveC/tlA5GmuHU59YiKbd0BNkIdvA8iGmTBZ2G43mkcB",
	"jDCWioaHbwOIUBipQ20U0iR8a6f+wkQsZ7oDM/8jtOZHFbab7XZQPmy11jGyMBTTD1hoAzxPi+KVj5IK",
	"LID2XQKsQ2C/BwYTS2rcIFv0UBjgbKioWgAzmJSoe9zrQvdsDXO7bu2yn7mRA94239bkfP5w7mEi1eJp",
	"0eznbOwaXnw57r3crqDsa0005gvYl49DpKMwqXOuL0qJn5l3MNYLZxVNX/8bYLq587WqP78DLo1UdIxP",
	"80A+aQd9cWC9bf2H65wnIF+8ESzb90ntiHjO+4Aa4Egtmgn0S1TrRX4iUyktdpGzYuhqu7FN7Ps9B0bS",
	"YAdsebJLeiFqpRQwDShGUkUYW3VomvJiX8ZxitxHwzc17Z6BcyzdXqPrpbdqOoLrQeZd9PxRlnew99yD",
	"r2tSLoPHA70awrRk9/vzYr6jWAZkvKr1+xNfEAwbRyU47098XhDcqVSJTPsTX8DhMiDTKM32K7xvJW6m",
	"qFOj9MXKLKvw2E7frcOmgrCEdCykNiyCaY7CSX78VAFih8Nd36+3m9T1Nv6LtZZsUO7fAqg0sl8ORMoz",
	"Df3eqsuXzx85PpOkmcEA8o/xXfxNftqoUi2jqNCOETnCRYfaKBqZquYrHiaoYVN3QJ9Q4yH5uUEuD5in",
	"b/lOL6531NJIZqLmxOs8S4aoQI5Kf55eXOs12jL1S2e2bD1OWo5c3WBJlqyXjfJewEZUen22I2/p7k6M",
	"pNdZGBpZrbdbhjklhqJ3VHYdji+6JCCcRSi0y32/wyTHKY0mCO1GkwQkU3zttH82mzWoe92QanyQz9UH",
	"n7qn784v34XtRrMxMQlfu9ywU4Fp2RUufG5nyxQFTRnpkMNGs3HkKd7EOag4be7ckzGaB8/SowlGdy4H",
	"dmmQZ4MU3dju4NB8KE69i0s1Tm672SxsjT5C1vjIwW9aitUVnl1o9qE4MN8+qvjoIiC/7rHxOTaz6Lhy",
	"pG8HH+Snl7Xm+IImU0IDLY9qNwBJb5ngE9MmP8+liiZoUGlHJDbIPZ3bIAZRpkZ+UgspKnd6a8mZHfl7",
	"hg5R8whL6NwfCzvmHazZLMYRzbghnVaz6Rq7eZa4vx7NmYePllN/Vu1zvU6dtRPqdV02Nw03zxgP+Tl7",
	"TTxcZo6kjDIOpZNsghw9Kj2/HvTXp2nh75zVKHFCY8fLUeeHa7mX9iX/WuA89T1WzMesp4i1nUNcH7RF",
	"ikwTcrMMSCrrbjCcKrQFjoLA2WZG5C2zfg9mjHO7gXFQbmEKY5B+B1OiSt4Q9yBfTSQvpN/blUnl+WS/",
	"B92z4hgqSaXrRUR2lYfDl8WVsF1dtcpYzYU7H8bOlScyXnzHCPaOW5UuW4aXWznT+u4Stzr+zl4Ygy5T",
	"hy/2njLFZTx/A85Jf7s/6adSjDiLDIQ+is3EUzl39ka5QhovAOdM+/sIR+32/nTrl4dOgPMI0wLRfjRU",
	"KRHC5W8FVPKae3A/Tbrx0oMLR1PXn3fPgW7tAkZKJg5HivO0TezwM3djx7XvraydAeTXFPs9S0tzxXLo",
	"cBfZSuSw2pPNlH0yllTS+6imC9XLlfhBMrJ7BjqzYjD2OhztMfZ77j70SGYi/hFjvgzX7ZgP6unlezQ1",
	"0T1cADO66Pt1z+pY9h8K7b0FdPOZ69UPwe/+kxq7U8MHel1e2AK/fas+jV31EL7MMjF+gGXamIW8K+4u",
	"ErumeUJNNKnM7vfqGOZxmvLFHy4SmVP2OXPqzyOczecnnN58Px7h/BOz989iuxWCy/zlheECqJBm4u73",
	"/4jQUmBFHdPMbwsXae37cQc0ZQerdtlNOel+x399UOWVR9d7dff81jKdbPdRKt20Env0albxfz9ulv8f",
	"AAD//9YXHkHONgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
