// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	externalRef1 "github.com/dcm-project/catalog-manager/api/v1alpha1/servicetypes/vm"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type string `json:"type"`
}

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status *string `json:"status,omitempty"`
}

// VM Provider-agnostic virtual machine specification.
//
// Includes common fields (serviceType, metadata, providerHints)
// plus VM-specific fields for compute, storage, and operating system.
//
// Providers translate this abstract specification to their native format.
type VM = externalRef1.VMSpec

// VMList Paginated list of VMs
type VMList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
	Vms           *[]VM   `json:"vms,omitempty"`
}

// ListVMsParams defines parameters for ListVMs.
type ListVMsParams struct {
	// MaxPageSize Maximum number of results per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateVMParams defines parameters for CreateVM.
type CreateVMParams struct {
	// Id Optional VM ID for idempotent creation
	Id *openapi_types.UUID `form:"id,omitempty" json:"id,omitempty"`
}

// CreateVMJSONRequestBody defines body for CreateVM for application/json ContentType.
type CreateVMJSONRequestBody = VM

// ApplyVMJSONRequestBody defines body for ApplyVM for application/json ContentType.
type ApplyVMJSONRequestBody = VM
